cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('clear/', views.cart_clear, name='cart_clear')
]

coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply')
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('shipping/<int:order_id>/', views.shipping_create, name='shipping_create'),
]

orders/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    coupon = models.ForeignKey('coupons.Coupon', related_name='orders', null=True, blank=True, on_delete=models.SET_NULL)
    discount = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created'])
        ]

    def __str__(self):
        return f"Order {self.id}"
    
    def get_total_cost(self):
        total_cost = self.get_total_cost_befor_discount()
        discount = self.get_discount()
        return total_cost - discount
    
    def get_total_cost_befor_discount(self):
        return sum(item.get_cost() for item in self.items.all())
    
    def get_discount(self):
        if self.discount:
            return self.get_total_cost_befor_discount() * (self.discount / 100)
        return 0
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey('shop.Product', related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"OrderItem {self.id}"
    
    def get_cost(self):
        return self.price * self.quantity
    

class Shipping(models.Model):
    DURATION_CHOICES = [
        ('standard', 'Standard'),
        ('express', 'Express'),
    ]
    order = models.OneToOneField(Order, related_name='shipping', on_delete=models.CASCADE)
    shipping_duration = models.CharField(max_length=10, choices=DURATION_CHOICES, default='standard')
    address = models.CharField(max_length=255)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=50)
    shipping_price = models.DecimalField(max_digits=8, decimal_places=2, default=0)

    def __str__(self):
        return f"Shipping for Order {self.order.id}"

orders/forms.py
from django import forms
from .models import Order
from .models import Shipping


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            'first_name',
            'last_name',
            'email',
        ]

        widgets = {
            'first_name': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control'
            }),
        }

class ShippingForm(forms.ModelForm):
    class Meta:
        model = Shipping
        fields = [
            'shipping_duration',
            'address',
            'postal_code',
            'city',
        ]

        widgets = {
            'shipping_duration': forms.Select(attrs={
                'class': 'form-control'
            }),
            'address': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'postal_code': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'city': forms.TextInput(attrs={
                'class': 'form-control'
            }),
        }

orders/views.py
from django.shortcuts import render, redirect
from cart.cart import Cart
from .forms import OrderForm, ShippingForm
from .models import OrderItem, Order
from .tasks import order_created

# Create your views here.

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.coupon.discount
            order.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item['product'],
                    price=item['price'],
                    quantity=item['quantity']
                )
            # cart.clear()
            order_created.delay(order.id)
            request.session['order_id'] = order.id
            return redirect('orders:shipping_create', order_id=order.id)
    else:
        form = OrderForm()
    return render(request, 'orders/create.html', {'cart': cart, 'form': form})

def shipping_create(request, order_id):
    cart = Cart(request)
    order = Order.objects.get(id=order_id)
    if request.method == 'POST':
        shipping_form = ShippingForm(request.POST)
        if shipping_form.is_valid():
            cd = shipping_form.cleaned_data
            shipping_type = cd['shipping_duration']
            shipping = shipping_form.save(commit=False)
            shipping.order = order
            if shipping_type == 'standard':
                shipping.shipping_price = 5.00
            else:
                shipping.shipping_price = 15.50
            shipping.save()
            return render(request, 'orders/verify.html', {'shipping': shipping})
    else:
        shipping_form = ShippingForm()
    return render(request, 'orders/shipping.html', {'order': order, 'shipping_form': shipping_form, 'cart': cart})

orders/templates/orders/include/order_summary.html
<!-- Order Summary -->
        <div class="col-lg-5">
            <div class="order-summary">
                <div class="summary-title">
                    <span>Order Summary</span>
                    {% with cart_total=cart|length %}
                    <span> {{ cart_total }} item{{ cart_total|pluralize }}</span>
                    {% endwith %}
                </div>
                
                <div class="cart-items">
                    {% for item in cart %}
                        {% with product=item.product %}
                            <div class="cart-item">
                                <div class="cart-item-img">
                                    <img src="{{ product.image.url }}">
                                </div>
                                <div class="cart-item-details">
                                    <div class="cart-item-title">{{ product.name }}</div>
                                    <div class="cart-item-qty">Qty: {{ item.quantity }}</div>
                                    <div class="cart-item-price">${{ item.total_price }}</div>
                                </div>
                            </div>
                        {% endwith %}
                    {% endfor %}
                </div>
                
                {% with total=cart.get_total_price.total_price %}
                <div class="summary-row">
                    <div>Subtotal</div>
                    <div>${{ total }}</div>
                </div>
                {% if cart.coupon %}
                    <div class="summary-row">
                        <div>Discount</div>
                        <div class="text-success">-${{ cart.get_discount }}</div>
                    </div>
                    <div class="summary-row total">
                        <div>Total</div>
                        <div>${{ cart.get_total_price_after_discount }}</div>
                    </div>
                {% else %}
                    <div class="summary-row total">
                        <div>Total</div>
                        <div>${{ total }}</div>
                    </div>
                {% endif %}
                {% endwith %}
                <!-- <div class="summary-row">
                    <div>Shipping</div>
                    <div>$29.99</div>
                </div> -->
                
                <!-- <div class="summary-row">
                    <div>Tax</div>
                    <div>${{ get_price_info }}</div>
                </div> -->
                <form action="{% url 'coupons:apply' %}" method="post">
                    {% csrf_token %}
                    <div class="summary-row">
                        <div class="promo-code mt-4">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Enter promo code" name="code">
                                <button class="btn btn-outline-primary">Apply</button>
                            </div>
                        </div>
                    </div>
                </form>